# This is a basic workflow to help you get started with Actions

name: ProductionRedaction
env:
    product_family: "redaction"
    
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ production ]
    paths:
       - 'content/redaction/**'
  pull_request:
    branches: [ production ]

  repository_dispatch:
    types: [production-complete]
    
  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      product_family: "redaction"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: groupdocs/products.groupdocs.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.101.0'
          extended: true

    - name: Remove unwanted folders
      run: |
        find ./content -mindepth 1 ! -regex '^./content/redaction\(/.*\)?' -delete
        ls content/ -all;

    - name: Build Redaction pages
      run: hugo --config "./production-config.toml" -b "https://products.groupdocs.com/" --disableKinds=taxonomy,category --cleanDestinationDir --minify
      
    - name: Prepare public folder
      run: |
        mv public/sitemap.xml public/$product_family.xml;
        rm public/index.html;
        mkdir public_home;
        mkdir public_home/sitemaps;
        mv public/$product_family.xml public_home/sitemaps/;
        #ls public -all;
        ls public/zh -all;
        #ls public_home -all;
        
    - name: Upload family sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public_home/sitemaps/redaction.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'sitemaps'

    - name: Upload default language
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/redaction'
        DEST_DIR: 'redaction' 
        
    - name: Upload en sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/en/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'en/redaction'
        
    - name: Upload zh folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/zh/redaction'
        DEST_DIR: 'zh/redaction' 

    - name: Upload zh sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/zh/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'zh/redaction'

    - name: Upload ru folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ru/redaction'
        DEST_DIR: 'ru/redaction'  

    - name: Upload ru sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/ru/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ru/redaction'
        
    - name: Upload fr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/fr/redaction'
        DEST_DIR: 'fr/redaction'    

    - name: Upload fr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/fr/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'fr/redaction'
        
    - name: Upload es folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2' 
        SOURCE_DIR: 'public/es/redaction'
        DEST_DIR: 'es/redaction' 

    - name: Upload es sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/es/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'es/redaction'

    - name: Upload de folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/de/redaction'
        DEST_DIR: 'de/redaction'  

    - name: Upload de sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/de/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'de/redaction'

    - name: Upload ja folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ja/redaction'
        DEST_DIR: 'ja/redaction'  

    - name: Upload ja sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/ja/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ja/redaction'

    - name: Upload ko folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ko/redaction'
        DEST_DIR: 'ko/redaction'  

    - name: Upload ko sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/ko/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ko/redaction'

    - name: Upload id folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/id/redaction'
        DEST_DIR: 'id/redaction'  

    - name: Upload id sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/id/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'id/redaction'

    - name: Upload it folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/it/redaction'
        DEST_DIR: 'it/redaction'  

    - name: Upload it sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/it/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'it/redaction'

    - name: Upload nl folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/nl/redaction'
        DEST_DIR: 'nl/redaction'  

    - name: Upload nl sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/nl/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'nl/redaction'

    - name: Upload ro folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ro/redaction'
        DEST_DIR: 'ro/redaction'  

    - name: Upload ro sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/ro/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ro/redaction'

    - name: Upload sk folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/sk/redaction'
        DEST_DIR: 'sk/redaction'  

    - name: Upload sk sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/sk/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'sk/redaction'

    - name: Upload sl folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/sl/redaction'
        DEST_DIR: 'sl/redaction'  

    - name: Upload sl sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/sl/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'sl/redaction'

    - name: Upload hi folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/hi/redaction'
        DEST_DIR: 'hi/redaction'  

    - name: Upload hi sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/hi/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'hi/redaction'

    - name: Upload tr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/tr/redaction'
        DEST_DIR: 'tr/redaction'  

    - name: Upload tr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/tr/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'tr/redaction'

    - name: Upload uk folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/uk/redaction'
        DEST_DIR: 'uk/redaction'  

    - name: Upload uk sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/uk/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'uk/redaction'

    - name: Upload lv folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/lv/redaction'
        DEST_DIR: 'lv/redaction'  

    - name: Upload lv sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/lv/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'lv/redaction'

    - name: Upload ms folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ms/redaction'
        DEST_DIR: 'ms/redaction'  

    - name: Upload ms sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/ms/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ms/redaction'

    - name: Invalidate cache
      env:
        API_ENDPOINT: ${{ secrets.CACHE_INVALIDATION_API_ENDPOINT }}
      run: |
        curl --write-out '%{http_code}' --silent --output /dev/null -d '{"website":"https://products.groupdocs.com/redaction/*"}' -H "Content-Type: application/json" -X POST "$API_ENDPOINT"
        curl --write-out '%{http_code}' --silent --output /dev/null -d '{"website":"https://products.groupdocs.com/**/redaction/*"}' -H "Content-Type: application/json" -X POST "$API_ENDPOINT"