# This is a basic workflow to help you get started with Actions

name: ProductionHome

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ production ]
    paths:
      - 'content/*'
  pull_request:
    branches: [ production ]

  repository_dispatch:
    types: [production-complete]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: groupdocs/products.groupdocs.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    # Step 2 - Sets up the latest version of Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true
    
    - name: Make Content folder for HomePage
      run: |
        cp -R content content_new;
        rm -R content;
        mkdir content;
        
        cp content_new/_index.md content;
        cp content_new/_index.zh.md content;
        cp content_new/_index.ru.md content;
        cp content_new/_index.fr.md content;
        cp content_new/_index.de.md content;
        cp content_new/_index.es.md content;
        cp content_new/_index.ja.md content;
        cp content_new/_index.ko.md content;

    - name: Build Home
      run: hugo --config "./production-config.toml" -c "content" -b "https://products.groupdocs.com" --disableKinds=page,section --minify

    - name: Copy static sitemap to public folder
      run: |
        cp sitemaps.xml public/sitemaps.xml;
        
    - name: Deploy Home to S3
      run: hugo deploy --config "./production-config.toml" --target "Home" 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
