# This is a basic workflow to help you get started with Actions

name: ProductionAssembly
env:
    product_family: "assembly"
    
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ production ]
    paths:
       - 'content/assembly/**'
  pull_request:
    branches: [ production ]

  repository_dispatch:
    types: [production-complete]
    
  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      product_family: "assembly"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: groupdocs/products.groupdocs.com
          ref: main
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.101.0'
          extended: true

    - name: Remove unwanted folders
      run: |
        find ./content -mindepth 1 ! -regex '^./content/assembly\(/.*\)?' -delete
        ls content/ -all;

    - name: Build Assembly pages
      run: hugo --config "./production-config.toml" -b "https://products.groupdocs.com/" --disableKinds=taxonomy,category --cleanDestinationDir --minify
      
    - name: Prepare public folder
      run: |
        mv public/sitemap.xml public/$product_family.xml;
        rm public/index.html;
        mkdir public_home;
        mkdir public_home/sitemaps;
        mv public/$product_family.xml public_home/sitemaps/;
        #ls public -all;
        ls public/zh -all;
        #ls public_home -all;
        
    - name: Upload family sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public_home/sitemaps/assembly.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'sitemaps'

    - name: Upload default language
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/assembly'
        DEST_DIR: 'assembly' 
        
    - name: Upload en sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/en/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'en/assembly'

    - name: Upload de folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/de/assembly'
        DEST_DIR: 'de/assembly'  

    - name: Upload de sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/de/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'de/assembly'
        
    - name: Upload es folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2' 
        SOURCE_DIR: 'public/es/assembly'
        DEST_DIR: 'es/assembly' 

    - name: Upload es sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/es/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'es/assembly'
        
    - name: Upload fa folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/fa/assembly'
        DEST_DIR: 'fa/assembly'    

    - name: Upload fa sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/fa/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'fa/assembly'
        
    - name: Upload fr folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/fr/assembly'
        DEST_DIR: 'fr/assembly'    

    - name: Upload fr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/fr/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'fr/assembly'
        
    - name: Upload id folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/id/assembly'
        DEST_DIR: 'id/assembly'    

    - name: Upload id sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/id/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'id/assembly'
        
    - name: Upload it folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/it/assembly'
        DEST_DIR: 'it/assembly'    

    - name: Upload it sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/it/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'it/assembly'

    - name: Upload ja folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ja/assembly'
        DEST_DIR: 'ja/assembly'  

    - name: Upload ja sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/ja/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ja/assembly'

    - name: Upload ko folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ko/assembly'
        DEST_DIR: 'ko/assembly'  

    - name: Upload ko sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/ko/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ko/assembly'

    - name: Upload pt folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/pt/assembly'
        DEST_DIR: 'pt/assembly'  

    - name: Upload pt sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/pt/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'pt/assembly'

    - name: Upload ru folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/ru/assembly'
        DEST_DIR: 'ru/assembly'  

    - name: Upload ru sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/ru/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ru/assembly'

    - name: Upload th folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/th/assembly'
        DEST_DIR: 'th/assembly'  

    - name: Upload th sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/th/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'th/assembly'

    - name: Upload uk folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/uk/assembly'
        DEST_DIR: 'uk/assembly'  

    - name: Upload uk sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/uk/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'uk/assembly'

    - name: Upload vi folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/vi/assembly'
        DEST_DIR: 'vi/assembly'  

    - name: Upload vi sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/vi/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'vi/assembly'
        
    - name: Upload zh folder
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'products.groupdocs.com'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS}}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'public/zh/assembly'
        DEST_DIR: 'zh/assembly' 

    - name: Upload zh sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products.groupdocs.com'
        file_path: 'public/zh/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'zh/assembly'

    - name: Invalidate cache
      env:
        API_ENDPOINT: ${{ secrets.CACHE_INVALIDATION_API_ENDPOINT }}
      run: |
        curl --write-out '%{http_code}' --silent --output /dev/null -d '{"website":"https://products.groupdocs.com/assembly/*"}' -H "Content-Type: application/json" -X POST "$API_ENDPOINT"
        curl --write-out '%{http_code}' --silent --output /dev/null -d '{"website":"https://products.groupdocs.com/**/assembly/*"}' -H "Content-Type: application/json" -X POST "$API_ENDPOINT"