# This is a basic workflow to help you get started with Actions

name: StagingBlog
env:
    product_family: "blog"
    
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ main ]
    paths:
       - 'content/blog/**'
  pull_request:
    branches: [ main ]

  repository_dispatch:
    types: [staging-complete]
    
  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: macos-latest
    env:
      product_family: "blog"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: groupdocs/products.groupdocs.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.101.0'
          extended: true

    - name: Remove unwanted folders
      run: |
        find ./content -mindepth 1 -not -regex './content/blog/.*' -delete
        ls -a content/
        ls -a content/blog

    - name: Build Blog pages
      run: hugo --config "./staging-config.toml" -b "https://products-qa.groupdocs.com/" --cleanDestinationDir --minify
      
    - name: Prepare public folder
      run: |
        mv public/sitemap.xml public/$product_family.xml;
        rm public/index.html;
        mkdir public_home;
        mkdir public_home/sitemaps;
        mv public/$product_family.xml public_home/sitemaps/;
        #ls public -all;
        ls -a public/zh;
        #ls public_home -all;
        

        
