name: StagingClassification
env:
    product_family: "classification"
on:
  repository_dispatch:
    types: [staging-complete]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      product_family: "classification"
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: groupdocs/products.groupdocs.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true

    - name: Remove unwanted folders
      run: |
        find ./content -mindepth 1 ! -regex '^./content/classification\(/.*\)?' -delete
        ls content/ -all;
    - name: Build Classification pages
      run: hugo --config "./classification-staging-config.toml" -b "products-qa.groupdocs.com" --disableKinds=taxonomy,category --cleanDestinationDir --minify
      
    - name: Prepare public folder
      run: |
        mv public/sitemap.xml public/$product_family.xml;
        rm public/index.html;
        ls public -all;
    - name: Deploy
      run: hugo deploy --config "./classification-staging-config.toml" --maxDeletes=-1 --target "classification" --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
  
