# This is a basic workflow to help you get started with Actions

name: StagingConversion
env:
    product_family: "conversion"
    
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ main ]
    paths:
       - 'content/conversion/**'
  pull_request:
    branches: [ main ]

  repository_dispatch:
    types: [staging-complete]
    
  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: macos-latest
    env:
      product_family: "conversion"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: groupdocs/products.groupdocs.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.101.0'
          extended: true

    - name: Remove unwanted folders
      run: |
        find ./content -mindepth 1 -not -regex './content/conversion/.*' -delete
        ls -a content/

    - name: Build Conversion pages
      run: hugo --config "./staging-config.toml" -b "https://products-qa.groupdocs.com/" --disableKinds=taxonomy,category --cleanDestinationDir --minify
      
    - name: Prepare public folder
      run: |
        mv public/sitemap.xml public/$product_family.xml;
        rm public/index.html;
        mkdir public_home;
        mkdir public_home/sitemaps;
        mv public/$product_family.xml public_home/sitemaps/;
        #ls public -all;
        ls -a public/zh;
        #ls public_home -all;
        
    - name: Upload family sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public_home/sitemaps/conversion.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'sitemaps'

    - name: Upload default language
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/conversion

    - name: Upload en sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/en/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'en/conversion'

    - name: Upload zh folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/zh/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/zh/conversion
    
    - name: Upload zh sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/zh/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'zh/conversion'

    - name: Upload ru folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/ru/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/ru/conversion

    - name: Upload ru sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/ru/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ru/conversion'
        
    - name: Upload fr folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/fr/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/fr/conversion

    - name: Upload fr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/fr/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'fr/conversion'
        
    - name: Upload es folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/es/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/es/conversion 

    - name: Upload es sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/es/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'es/conversion'

    - name: Upload de folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/de/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/de/conversion  

    - name: Upload de sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/de/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'de/conversion'

    - name: Upload ja folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/ja/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/ja/conversion  

    - name: Upload ja sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/ja/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ja/conversion'

    - name: Upload ko folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/ko/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/ko/conversion

    - name: Upload ko sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/ko/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ko/conversion'
    
    - name: Upload id folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/id/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/id/conversion  

    - name: Upload id sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/id/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'id/conversion'
    
    - name: Upload uk folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/uk/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/uk/conversion  

    - name: Upload uk sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/uk/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'uk/conversion'

    - name: Upload bg folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/bg/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/bg/conversion  

    - name: Upload bg sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/bg/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'bg/conversion'
    
    - name: Upload tr folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/tr/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/tr/conversion  

    - name: Upload tr sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/tr/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'tr/conversion'
    
    - name: Upload pl folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/pl/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/pl/conversion  

    - name: Upload pl sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/pl/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'pl/conversion'

    - name: Upload pt folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/pt/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/pt/conversion  

    - name: Upload pt sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/pt/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'pt/conversion'

    - name: Upload ar folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/ar/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/ar/conversion  

    - name: Upload ar sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/ar/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'ar/conversion'

    - name: Upload th folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/th/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/th/conversion  

    - name: Upload th sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/th/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'th/conversion'        

    - name: Upload vi folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/vi/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/vi/conversion  

    - name: Upload vi sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/vi/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'vi/conversion'  

    - name: Upload it folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/it/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/it/conversion  

    - name: Upload it sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/it/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'it/conversion'   

    - name: Upload nl folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/nl/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/nl/conversion  

    - name: Upload nl sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/nl/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'nl/conversion'  

    - name: Upload cs folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/cs/conversion --acl public-read --no-progress --region us-west-2
      working-directory: public/cs/conversion  

    - name: Upload cs sitemap
      uses: swimlane/s3-upload-file-action@main
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_ACCESS}}
        aws_bucket: 'products-qa.groupdocs.com'
        file_path: 'public/cs/sitemap.xml'
        file_mime_type: 'application/xml'
        dest_dir: 'cs/conversion'                         