name: StagingConversionInvalidateCache

on:
  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest
    env:
      product_family: "conversion"

    steps:
    - name: Invalidate cache
      env:
        API_ENDPOINT: ${{ secrets.CACHE_INVALIDATION_API_ENDPOINT }}
      run: |
        curl --write-out '%{http_code}' --silent --output /dev/null -d '{"website":"https://products-qa.groupdocs.com/conversion/*"}' -H "Content-Type: application/json" -X POST "$API_ENDPOINT"
       


        
    

    





    



