name: StagingTotalIndexPages
env:
    product_family: "total"
    
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the mentioned branches
  push:
    branches: [ main ]
    paths:
       - 'content/total/**'
  pull_request:
    branches: [ main ]

  repository_dispatch:
    types: [staging-complete]
    
  # Allows the workflow run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      product_family: "total"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout content from products.groupdocs.com repo
      uses: actions/checkout@main
      with:
          repository: groupdocs/products.groupdocs.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.101.0'
          extended: true

    - name: Remove all except total _index pages
      run: |
        find ./content -mindepth 1 -type f -not -regex './content/total/.*_index.*' -delete
        ls content/ -all;

    - name: Build pages
      run: hugo --config "./total-staging-config.toml" -b "https://products-qa.groupdocs.com/" --disableKinds=taxonomy,category --cleanDestinationDir --minify
      
    - name: Prepare public folder
      run: |
        rm public/index.html;

    - name: Upload en folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/total --acl public-read --no-progress --region us-west-2
      working-directory: public/total        
       
    - name: Upload de folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/de/total --acl public-read --no-progress --region us-west-2
      working-directory: public/de/total

    - name: Upload es folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/es/total --acl public-read --no-progress --region us-west-2
      working-directory: public/es/total

    - name: Upload fa folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/fa/total --acl public-read --no-progress --region us-west-2
      working-directory: public/fa/total

    - name: Upload fr folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/fr/total --acl public-read --no-progress --region us-west-2
      working-directory: public/fr/total

    - name: Upload id folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/id/total --acl public-read --no-progress --region us-west-2
      working-directory: public/id/total

    - name: Upload it folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/it/total --acl public-read --no-progress --region us-west-2
      working-directory: public/it/total

    - name: Upload ja folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/ja/total --acl public-read --no-progress --region us-west-2
      working-directory: public/ja/total

    - name: Upload ko folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/ko/total --acl public-read --no-progress --region us-west-2
      working-directory: public/ko/total

    - name: Upload pt folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/pt/total --acl public-read --no-progress --region us-west-2
      working-directory: public/pt/total

    - name: Upload ru folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/ru/total --acl public-read --no-progress --region us-west-2
      working-directory: public/ru/total

    - name: Upload th folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/th/total --acl public-read --no-progress --region us-west-2
      working-directory: public/th/total

    - name: Upload uk folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/uk/total --acl public-read --no-progress --region us-west-2
      working-directory: public/uk/total

    - name: Upload vi folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/vi/total --acl public-read --no-progress --region us-west-2
      working-directory: public/vi/total

    - name: Upload zh folder
      run: AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS}} aws s3 sync . s3://products-qa.groupdocs.com/zh/total --acl public-read --no-progress --region us-west-2
      working-directory: public/zh/total  
      

    - name: Invalidate cache
      env:
        API_ENDPOINT: ${{ secrets.CACHE_INVALIDATION_API_ENDPOINT }}
      run: |
        curl --write-out '%{http_code}' --silent --output /dev/null -d '{"website":"https://products-qa.groupdocs.com/total/*"}' -H "Content-Type: application/json" -X POST "$API_ENDPOINT"
        curl --write-out '%{http_code}' --silent --output /dev/null -d '{"website":"https://products-qa.groupdocs.com/*/total/*"}' -H "Content-Type: application/json" -X POST "$API_ENDPOINT"
